# game/ai_strategies_const.py
# Názvy stratégií pre logovanie

# Leader stratégie
CERTAIN_TRICK = "S1-CERTAIN_TRICK"
PROBABLE_TRICK = "S2-PROBABLE_TRICK"
FORCING = "S3-FORCING"
PASSIVE = "S4-PASSIVE"
TRUMP_DECLARE = "S5-TRUMP_DECLARE"

# Follower stratégie
BEAT_TRICK = "S6-BEAT_TRICK"
PROTECT_TEN = "S7-PROTECT_TEN"
SAFE_DISCARD = "S9-SAFE_DISCARD"

# Bidding stratégie
BID_ESTIMATE = "S10-BID_ESTIMATE"
PASS_FOR_TRUMP = "S11-PASS_FOR_TRUMP"
RAISE_AFTER_TALON = "S12-RAISE_AFTER_TALON"
SECURE_TRUMP_BID = "S14-SECURE_TRUMP_BID"

# Zahadzovaie
SMART_DISCARD = "S13-SMART_DISCARD"

#Najnovšie
EXHAUST_SUIT = "S18-EXHAUST_SUIT"
ENDGAME = "S21-ENDGAME"
TRACK_BIDDER = "S23-TRACK_BIDDER"
LONG_SUIT_BID = "S16-LONG_SUIT_BID"
PASSIVE_BID = "S27-PASSIVE_BID"